"""empty message

Revision ID: 45c907f427fc
Revises: 8a17b6181be4
Create Date: 2022-08-10 13:56:31.688515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c907f427fc'
down_revision = '8a17b6181be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_booking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_booking')
    # ### end Alembic commands ###
